### ISSUE TITLE
Terrain radar issue

### ISSUE THREAD

**Issue by kolos26** [Ariakim-Taiyo/GeoFs-ILS#5]
@Ariakim-Taiyo 
Hi,
I'm currently playing a lot with this addon. The points of the terrain radar do not turn to red, they are staying yellow, even if I'm facing a high mountain, just about to crash it. I couldn't find any error messages in the console. I don't know, if it affects the addon (I guess it won't), but I'm using GeoFS 3.5, not the legacy version.

Kind regards,
Kolos

**Comment by kolos26** [comment]
I have checked a few things in the script. Somehow, when I'm using 3.5 the getGroundAltitude function always returns the ground altitude of the plane's coordinates. I'm not sure, if we can fix it.

**Comment by Ariakim-Taiyo** [comment]
By nature this addon is difficult to debug, for the same reason that shaders are.
I believe that the entire radar display is rotated incorrectly by 90 degrees in some direction, but that should be a quick fix if I revisit this. You can adjust `directionStart` to include a 90 degree offset and see if that helps.
getGroundAltitude should return the ground elevation at a point specified by 
the parameters that you pass, in my case `(x1+x2, y1+y2)`.
I haven't updated this since legacy but I don't see any reason why it shouldn't work on 3.5 just yet.
You can also take a look at the segment of the canvas rendering function that handles the terrainPoints array, and adjust some of the values used to assign colors to make them more sensitive.

**Comment by kolos26** [comment]
I have checked and in the terrarinPoints array the same height is for every point. The canvas seems to be perfect.

**Comment by Ariakim-Taiyo** [comment]
It appears that the function was slightly altered after legacy so that it uses an array as an input.
The function should now be fixed.

**Comment by kolos26** [comment]
Thank you for the fast bugfix! Now it works well on 3.5! Best regards, Kolos
